version: '3.8'
services:
  api:
    build:
      context: .
    command: sh -c "pnpm run run-db-migrations && pnpm run dev"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '4000:${SERVER_PORT}'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env

  db:
    image: mysql:8
    restart: always
    expose:
      - '3306'
    ports:
      - '3306:3306'
    volumes:
      - mysqldata:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQ_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 20s
      retries: 10

volumes:
  mysqldata:

networks:
  todo_api_network:
