version: '3.0'
services:
  api:
    build:
      context: .
    command: pnpm run dev
    depends_on:
      - db
    ports:
      - '4000:3333'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env

  db:
    image: mysql:8
    restart: always
    expose:
      - '3306'
    ports:
      - '3306:3306'
    volumes:
      - mysqldata:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

volumes:
  mysqldata:

networks:
  todo_api_network:
